---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
vars:
  dir: frontend

tasks:
  dev:
    desc: "[FRONTEND] start up development server"
    cmd: bun dev
    dir: "{{.dir}}"
  lint:
    desc: "[FRONTEND] lint"
    cmd: bun lint
    dir: "{{.dir}}"
  lint:fix:
    desc: "[FRONTEND] fix linting errors"
    cmd: bun lint --fix
    dir: "{{.dir}}"
  install:
    desc: "[FRONTEND] install dependencies"
    cmd: "bun install"
    aliases:
      - i
      - deps
    dir: "{{.dir}}"
  unused:
    desc: "Check for unused dependencies on the frontend"
    cmd: "npx knip"
    dir: "{{.dir}}"
    ignore_error: true
